export const abouts = [
    {
        "name":"My Bio",
        "id": 1,
        "tier":"Tier: D",
        "universe":"",
        "weight": 81,
        "airspeed": 1019,
        "fallingspeed": 1770,
        "fastfall" :2832,
        "dash": 1936,
        "runspeed":1760,
        "image":"/images/ultimate/1.png",
        "link":"/html/bio.html",
    },
    {
        "name":"Programming Languages",
        "id": 1,
        "tier":"Tier: D",
        "universe":"",
        "weight": 81,
        "airspeed": 1019,
        "fallingspeed": 1770,
        "fastfall" :2832,
        "dash": 1936,
        "runspeed":1760,
        "image":"/images/ultimate/1.png",
        "link":"/html/languages.html",
    },
    {
        "name":"Design Skills",
        "id": 1,
        "tier":"Tier: D",
        "universe":"",
        "weight": 81,
        "airspeed": 1019,
        "fallingspeed": 1770,
        "fastfall" :2832,
        "dash": 1936,
        "runspeed":1760,
        "image":"/images/ultimate/1.png",
        "link":"/html/design.html",
    },
    {
        "name":"Experience",
        "id": 1,
        "tier":"Tier: D",
        "universe":"",
        "weight": 81,
        "airspeed": 1019,
        "fallingspeed": 1770,
        "fastfall" :2832,
        "dash": 1936,
        "runspeed":1760,
        "image":"/images/ultimate/1.png",
        "link":"/html/experience.html",
    },
    {
        "name":"Soft Skills",
        "id": 1,
        "tier":"Tier: D",
        "universe":"",
        "weight": 81,
        "airspeed": 1019,
        "fallingspeed": 1770,
        "fastfall" :2832,
        "dash": 1936,
        "runspeed":1760,
        "image":"/images/ultimate/1.png",
        "link":"/html/soft.html",
    },
];