export const artwork = [
    {
        "name":"Photoshop Retouch",
        "id": 1,
        "tier":"Tier: D",
        "universe":"",
        "weight": 81,
        "airspeed": 1019,
        "fallingspeed": 1770,
        "fastfall" :2832,
        "dash": 1936,
        "runspeed":1760,
        "image":"/images/art/final_retouch_pectol.jpg",
        "link":"/images/art/final_retouch_pectol.jpg",
    },
    {
        "name":"Album Cover Recreation",
        "id": 1,
        "tier":"Tier: D",
        "universe":"",
        "weight": 81,
        "airspeed": 1019,
        "fallingspeed": 1770,
        "fastfall" :2832,
        "dash": 1936,
        "runspeed":1760,
        "image":"/images/art/album_cover_pectol.jpg",
        "link":"/images/art/album_cover_pectol.jpg",
    },
    {
        "name":"Space Hut",
        "id": 1,
        "tier":"Tier: D",
        "universe":"",
        "weight": 81,
        "airspeed": 1019,
        "fallingspeed": 1770,
        "fastfall" :2832,
        "dash": 1936,
        "runspeed":1760,
        "image":"/images/ultimate/1.png",
        "link":"https://spacehut.netlify.app",
    },
    {
        "name":"Art",
        "id": 1,
        "tier":"Tier: D",
        "universe":"",
        "weight": 81,
        "airspeed": 1019,
        "fallingspeed": 1770,
        "fastfall" :2832,
        "dash": 1936,
        "runspeed":1760,
        "image":"/images/ultimate/1.png",
        "link":"/html/art.html",
    },
];