export const projects = [
    {
        "name":"Canvas Redesign",
        "id": 1,
        "tier":"Tier: D",
        "universe":"",
        "weight": 81,
        "airspeed": 1019,
        "fallingspeed": 1770,
        "fastfall" :2832,
        "dash": 1936,
        "runspeed":1760,
        "image":"/images/ultimate/1.png",
        "link":"/html/canvas.html",
    },
    {
        "name":"Calculator",
        "id": 1,
        "tier":"Tier: D",
        "universe":"",
        "weight": 81,
        "airspeed": 1019,
        "fallingspeed": 1770,
        "fastfall" :2832,
        "dash": 1936,
        "runspeed":1760,
        "image":"/images/ultimate/1.png",
        "link":"/html/calc.html",
    },
    //{
      //  "name":"My Avatar Bender",
     //   "id": 1,
      //  "tier":"Tier: D",
     //   "universe":"",
       // "weight": 81,
      //  "airspeed": 1019,
      //  "fallingspeed": 1770,
     //  "fastfall" :2832,
      //  "dash": 1936,
      //  "runspeed":1760,
      //  "image":"/images/ultimate/1.png",
     //   "link":"https://myavatarbender.netlify.app",
   // },
  //  {
      //  "name":"Space Hut",
     //   "id": 1,
     //   "tier":"Tier: D",
       // "universe":"",
      //  "weight": 81,
     //   "airspeed": 1019,
      //  "fallingspeed": 1770,
      //  "fastfall" :2832,
     //   "dash": 1936,
      //  "runspeed":1760,
     //   "image":"/images/ultimate/1.png",
     //   "link":"https://spacehut.netlify.app",
   // },
    {
        "name":"Art",
        "id": 1,
        "tier":"Tier: D",
        "universe":"",
        "weight": 81,
        "airspeed": 1019,
        "fallingspeed": 1770,
        "fastfall" :2832,
        "dash": 1936,
        "runspeed":1760,
        "image":"/images/ultimate/1.png",
        "link":"/html/art.html",
    },
    {
        "name":"Digital Media",
        "id": 1,
        "tier":"Tier: D",
        "universe":"",
        "weight": 81,
        "airspeed": 1019,
        "fallingspeed": 1770,
        "fastfall" :2832,
        "dash": 1936,
        "runspeed":1760,
        "image":"/images/ultimate/1.png",
        "link":"/html/dgm.html",
    },
];
